//! The spec suite: what a second implementation is held to.
//!
//! Everything else in `tests/` checks this crate against itself. This file checks it against
//! `spec/v1/`, which is the artefact a Java or Spring Boot producer conforms to and the only thing
//! standing between two implementations and two subtly different documents.
//!
//! It has two halves, and they fail for different reasons:
//!
//! - **The meta-schema** ([`spec/v1/contract.schema.json`]) says what a well-formed contract is.
//!   A failure here means this crate emits something the spec does not describe — either the
//!   crate grew a field the spec has not learned, or the spec claims something the crate never
//!   guaranteed. Both are the spec being wrong, because the spec is what another language reads.
//! - **The conformance corpus** (`spec/v1/conformance/`) says what one specific input produces.
//!   A failure here means a rendering changed. That is sometimes intended — regenerate with
//!   `TERRACE_SPEC_BLESS=1 cargo test --all-features --test spec` and read the diff, which is the
//!   point: the diff is the change a second implementation now has to match.
//!
//! The corpus is checked against the meta-schema too. A case that no longer validates is the one
//! failure mode a corpus alone cannot catch: an expectation that was blessed while wrong.

#![cfg(feature = "schema")]
#![expect(dead_code, reason = "fixtures are read by the derive, not at runtime")]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use serde_json::{Value as Json, json};
use terrace_config::Terrace;
use terrace_config::schema::{App, Contract, Describe, External, ExternalVar, Unknown};

/// The version string every corpus document carries in place of the real one.
///
/// The producer's version moves on every release and says nothing about the rendering, so leaving
/// it in would make each release a corpus-wide diff that hides the one line that mattered. A
/// sentinel rather than the real number, because a reference document carrying a version it was
/// not generated by is a small lie a reader has no way to detect.
const CONFORMANCE_VERSION: &str = "0.0.0-conformance";

/// Set to regenerate the corpus instead of checking it.
const BLESS: &str = "TERRACE_SPEC_BLESS";

fn spec_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("spec")
        .join("v1")
}

// ---------------------------------------------------------------------------------------------
// Fixtures
//
// One per case, and deliberately not shared: a corpus case is a claim about what a specific input
// renders to, so a fixture edited for one case's sake would silently restate every other case.
// ---------------------------------------------------------------------------------------------

/// The smallest thing that is still a contract: one key, one layer, nothing annotated.
#[derive(Deserialize, Serialize, Describe)]
struct Minimal {
    /// Bundle directory the readiness probe checks.
    #[serde(default = "default_dist")]
    dist_dir: String,
}

// Hand-written rather than derived, in every fixture here, and it is not boilerplate: the
// *observed* default is what `with_defaults_from` serialises, so a derived `Default` would publish
// `""` for a field whose `#[serde(default = "…")]` supplies `public`. A corpus document is read by
// somebody implementing this in another language, and one whose defaults contradict its own
// annotations teaches the wrong thing.
impl Default for Minimal {
    fn default() -> Self {
        Self {
            dist_dir: default_dist(),
        }
    }
}

/// Every field of a key that a producer can be asked to fill.
#[derive(Deserialize, Serialize, Describe)]
#[serde(deny_unknown_fields)]
struct Full {
    /// Bundle directory the readiness probe checks.
    #[serde(default = "default_dist")]
    dist_dir: String,
    /// Base URL every outbound request is resolved against.
    ///
    /// No default and not optional, so some layer has to supply it — which is what `required`
    /// says, and which is not what a JSON Schema `required` list would say about the rendered
    /// document.
    api_base: String,
    /// How much the service says.
    #[config(values)]
    #[serde(default)]
    log_level: LogLevel,
    /// Fraction of requests sampled for tracing.
    #[config(range(min = 0.0, max = 1.0))]
    #[serde(default)]
    sample_rate: f64,
    /// Methods every route admits.
    #[config(element_values)]
    #[serde(default)]
    methods: Vec<Method>,
    #[config(nested)]
    github: Github,
}

impl Default for Full {
    fn default() -> Self {
        Self {
            dist_dir: default_dist(),
            // No `#[serde(default)]`, so no layer-independent value exists and the key is
            // `required`. What this field holds here is never published: a required key renders
            // `default: null`, which is the assertion `full-surface` pins.
            api_base: String::new(),
            log_level: LogLevel::default(),
            sample_rate: 0.0,
            methods: Vec::new(),
            github: Github::default(),
        }
    }
}

#[derive(Deserialize, Serialize, Default, Describe)]
struct Github {
    /// User whose repositories are listed.
    #[serde(alias = "user")]
    username: String,
    /// Bearer token lifting the API rate limit.
    ///
    /// Supply it as a mounted file, so the value never reaches the process environment.
    #[config(secret)]
    token: Option<String>,
    /// Revalidation interval in seconds.
    #[config(note = "permanent")]
    #[serde(default)]
    ttl_secs: u64,
}

/// A container whose keys the environment cannot name.
///
/// `rename_all = "camelCase"` is the ordinary way to arrive here: the environment layer folds a
/// name to lower case on the way in, and a camel-cased path never comes back through the fold. The
/// key is real and the document can supply it; no variable can, and `unreachable` is what says
/// which of those two situations a consumer is looking at.
#[derive(Deserialize, Serialize, Describe)]
#[serde(rename_all = "camelCase")]
struct Unnameable {
    /// Where the bundle is read from.
    #[serde(default = "default_dist")]
    dist_dir: String,
    /// How long a rendered page stays fresh.
    #[serde(default)]
    max_age_secs: u64,
}

impl Default for Unnameable {
    fn default() -> Self {
        Self {
            dist_dir: default_dist(),
            max_age_secs: 0,
        }
    }
}

#[derive(Deserialize, Serialize, Default, Describe)]
#[serde(rename_all = "lowercase")]
enum LogLevel {
    Trace,
    Debug,
    #[default]
    Info,
    Warn,
}

#[derive(Deserialize, Serialize, Default, Describe)]
#[serde(rename_all = "UPPERCASE")]
enum Method {
    #[default]
    Get,
    Post,
}

fn default_dist() -> String {
    "public".to_owned()
}

// ---------------------------------------------------------------------------------------------
// The cases
// ---------------------------------------------------------------------------------------------

/// Every corpus case, by directory name.
///
/// The `App` is fixed rather than derived: `revision` and `created` are build facts, and a corpus
/// carrying them would be a corpus that changes on every run.
fn cases() -> Vec<(&'static str, Contract)> {
    vec![
        ("minimal", minimal()),
        ("full-surface", full_surface()),
        ("unnameable-key", unnameable_key()),
    ]
}

fn minimal() -> Contract {
    Terrace::new("MINIMAL_")
        .schema::<Minimal>()
        .with_defaults_from(&Minimal::default())
        .expect("the default config serialises")
        .into_contract(App::new("minimal").version("1.0.0"))
        .build()
        .expect("the contract has nothing to refuse")
}

fn full_surface() -> Contract {
    Terrace::new("PORTFOLIO_")
        .reserve("PORTFOLIO_PROFILE")
        .schema::<Full>()
        .with_defaults_from(&Full::default())
        .expect("the default config serialises")
        .into_contract(App::new("portfolio").version("2.5.0"))
        .external(
            External::new()
                .var(
                    ExternalVar::new("PORT")
                        .owner("runtime")
                        .ty("u16")
                        .default("8080")
                        .docs("Bind port. Read by the server toolchain, not by this loader."),
                )
                .var(ExternalVar::new("RUST_LOG").owner("tracing").ty("String"))
                .ignore("KUBERNETES_*")
                .ignore("HOSTNAME")
                .unknown(Unknown::Reject),
        )
        .build()
        .expect("the contract has nothing to refuse")
}

fn unnameable_key() -> Contract {
    Terrace::new("EDGE_")
        .schema::<Unnameable>()
        .with_defaults_from(&Unnameable::default())
        .expect("the default config serialises")
        .into_contract(App::new("edge").version("1.0.0"))
        .build()
        .expect("the contract has nothing to refuse")
}

// ---------------------------------------------------------------------------------------------
// The meta-schema
// ---------------------------------------------------------------------------------------------

fn meta_schema() -> Json {
    let path = spec_dir().join("contract.schema.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} could not be read: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{} is not JSON: {e}", path.display()))
}

fn validator(schema: &Json) -> jsonschema::Validator {
    jsonschema::validator_for(schema).expect("the meta-schema is a valid JSON Schema")
}

/// The meta-schema restricted to its `schema` half, for the `json` rendering.
///
/// Built by pointing the root at `#/$defs/schema` rather than by resolving
/// `contract.schema.json#schema` through a registry: the definitions are in the same document, so
/// a local pointer reaches them, and a test that needed a resolver would be testing the resolver.
fn schema_half_validator(meta: &Json) -> jsonschema::Validator {
    let mut sub = meta.clone();
    let object = sub.as_object_mut().expect("the meta-schema is an object");
    for key in ["type", "properties", "required", "title", "description"] {
        object.remove(key);
    }
    object.insert(
        "$id".to_owned(),
        json!("https://terrace.dev/spec/v1/schema-only.json"),
    );
    object.insert("$ref".to_owned(), json!("#/$defs/schema"));
    validator(&sub)
}

fn assert_valid(validator: &jsonschema::Validator, instance: &Json, what: &str) {
    let errors: Vec<String> = validator
        .iter_errors(instance)
        .map(|e| format!("  at `{}`: {e}", e.instance_path()))
        .collect();
    assert!(
        errors.is_empty(),
        "{what} does not satisfy spec/v1/contract.schema.json:\n{}",
        errors.join("\n")
    );
}

#[test]
fn the_meta_schema_is_itself_a_valid_json_schema() {
    // Compiling it is the check. A meta-schema with a dangling `$ref` or a misspelt keyword
    // validates everything silently, which is worse than validating nothing.
    let _ = validator(&meta_schema());
}

#[test]
fn every_case_satisfies_the_meta_schema() {
    let meta = meta_schema();
    let validator = validator(&meta);

    for (name, contract) in cases() {
        let json = as_json(&contract);
        assert_valid(&validator, &json, &format!("the `{name}` case"));
    }
}

#[test]
fn the_schema_half_satisfies_the_meta_schema_on_its_own() {
    // The `json` rendering is published as an artefact of its own, so the subschema has to be
    // reachable and correct without the envelope around it.
    let validator = schema_half_validator(&meta_schema());

    for (name, contract) in cases() {
        let json = serde_json::to_value(&contract.schema).expect("the schema half serialises");
        assert_valid(
            &validator,
            &json,
            &format!("the `{name}` case's schema half"),
        );
    }
}

#[test]
fn the_stored_corpus_satisfies_the_meta_schema() {
    // Not the same check as `every_case_satisfies_the_meta_schema`: that one validates what the
    // crate renders *now*, this one validates what was blessed. An expectation blessed while
    // wrong passes the first and fails here.
    let validator = validator(&meta_schema());

    for (name, _) in cases() {
        let path = case_path(name);
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue; // `the_corpus_matches_what_the_crate_renders` is what reports a missing case.
        };
        let json: Json = serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("{} is not JSON: {e}", path.display()));
        assert_valid(&validator, &json, &format!("the stored `{name}` case"));
    }
}

// ---------------------------------------------------------------------------------------------
// The corpus
// ---------------------------------------------------------------------------------------------

fn case_path(name: &str) -> PathBuf {
    spec_dir()
        .join("conformance")
        .join(name)
        .join("contract.json")
}

/// The document with the one field a corpus cannot pin: see [`CONFORMANCE_VERSION`].
///
/// Substituted on the `Contract` rather than on the JSON it renders to, so that the stored file is
/// what `to_json` actually emits — same field order, same bytes. Round-tripping through
/// `serde_json::Value` sorts every object alphabetically, which would leave the corpus full of
/// documents no producer ever writes and no reader should imitate.
fn normalise(contract: &Contract) -> Contract {
    let mut contract = contract.clone();
    CONFORMANCE_VERSION.clone_into(&mut contract.producer.version);
    contract
}

fn rendered(contract: &Contract) -> String {
    let mut text = normalise(contract).to_json().expect("the contract renders");
    text.push('\n');
    text
}

/// The stored document, parsed — for the checks that validate rather than compare.
fn as_json(contract: &Contract) -> Json {
    serde_json::from_str(&rendered(contract)).expect("the rendered contract parses")
}

#[test]
fn the_corpus_matches_what_the_crate_renders() {
    let bless = std::env::var_os(BLESS).is_some();
    let mut stale: BTreeMap<&str, String> = BTreeMap::new();

    for (name, contract) in cases() {
        let path = case_path(name);
        let expected = rendered(&contract);

        if bless {
            std::fs::create_dir_all(path.parent().expect("the case has a directory"))
                .expect("the case directory can be created");
            std::fs::write(&path, expected.as_bytes()).expect("the case can be written");
            continue;
        }

        match std::fs::read_to_string(&path) {
            Ok(found) => {
                let found = found.replace("\r\n", "\n");
                if found != expected {
                    stale.insert(name, first_difference(&found, &expected));
                }
            }
            Err(e) => {
                stale.insert(name, format!("could not be read: {e}"));
            }
        }
    }

    let mut report = String::new();
    for (name, detail) in &stale {
        write!(report, "\n`{name}`: {detail}").expect("writing to a String cannot fail");
    }

    assert!(
        stale.is_empty(),
        "the conformance corpus no longer matches what this crate renders. If the change is \
         intended, regenerate with `{BLESS}=1 cargo test --all-features --test spec` and read the \
         diff — it is the change every other implementation now has to match.\n{report}"
    );
}

/// The first line the two differ on, which is what a reader needs and what a whole-document dump
/// buries.
fn first_difference(found: &str, expected: &str) -> String {
    for (line, (a, b)) in found.lines().zip(expected.lines()).enumerate() {
        if a != b {
            return format!("line {}: stored `{a}`, rendered `{b}`", line + 1);
        }
    }
    format!(
        "stored document has {} lines, rendered has {}",
        found.lines().count(),
        expected.lines().count()
    )
}

// ---------------------------------------------------------------------------------------------
// The claims the meta-schema makes that only the crate can confirm
// ---------------------------------------------------------------------------------------------

#[test]
fn the_producer_names_itself_and_its_loader() {
    let json = as_json(&minimal());

    assert_eq!(json["producer"]["name"], json!("terrace-config"));
    // The field a consumer needs before it applies any `text_constraint`: those patterns were
    // measured against this library's environment reads and describe no other.
    assert_eq!(json["producer"]["loader"], json!("figment"));
}

#[test]
fn a_key_the_environment_cannot_name_says_why() {
    // The invariant the meta-schema encodes as a conditional. It holds because a producer that
    // publishes no spelling always has a reason to publish, and a consumer meeting a bare null
    // would have to guess between "the document is the only layer" and "another key's variable
    // fills this one".
    let json = as_json(&unnameable_key());
    let keys = json["schema"]["keys"].as_array().expect("keys is an array");

    let unnameable: Vec<_> = keys.iter().filter(|key| key["env"].is_null()).collect();
    assert!(
        !unnameable.is_empty(),
        "the fixture is supposed to produce a key no variable names"
    );
    for key in unnameable {
        assert_eq!(key["unreachable"], json!("unnameable"), "{key}");
    }
}
